# IMPORTING THE NECESSARY PACKAGES

In [24]:
import pandas as pd
import numpy as np
import pickle
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# LOADING THE REQUIRED DATASET

In [16]:
data=pd.read_csv('dataset/dataset.csv')
data

ID  Age Gender  Experience  Income  ZIP Code  Family  CCAvg  \
0        1   25      M           1    49.0     91107       4    1.6   
1        2   45      M          19    34.0     90089       3    1.5   
2        3   39      M          15    11.0     94720       1    1.0   
3        4   35      M           9   100.0     94112       1    2.7   
4        5   35      M           8    45.0     91330       4    1.0   
...    ...  ...    ...         ...     ...       ...     ...    ...   
4995  4996   29    NaN           3    40.0     92697       1    1.9   
4996  4997   30    NaN           4    15.0     92037       4    0.4   
4997  4998   63    NaN          39    24.0     93023       2    0.3   
4998  4999   65    NaN          40    49.0     90034       3    0.5   
4999  5000   28    NaN           4    83.0     92612       3    0.8   

      Education  Mortgage Home Ownership Personal Loan  Securities Account  \
0             1         0     Home Owner             0                   1   
1             1         0           Rent             0                   1   
2             1         0           Rent             0                   0   
3             2         0           Rent             0                   0   
4             2         0           Rent             0                   0   
...         ...       ...            ...           ...                 ...   
4995          3         0            NaN             0                   0   
4996          1        85            NaN             0                   0   
4997          3         0            NaN             0                   0   
4998          2         0            NaN             0                   0   
4999          1         0            NaN             0                   0   

      CD Account  Online  CreditCard  
0              0     0.0           0  
1              0     0.0           0  
2              0     0.0           0  
3              0     0.0           0  
4              0     0.0           1  
...          ...     ...         ...  
4995           0     1.0           0  
4996           0     1.0           0  
4997           0     0.0           0  
4998           0     1.0           0  
4999           0     1.0           1  

[5000 rows x 16 columns]

# PREPROCESSING THE DATA

SIMPLE IMPUTERS
used this to replace the missed value with the mean

COLUMN TRANSFORMER
used this to create a pipeline that will tansform all the colums to a mathematical vectorized form

OneHotEncoder
used this to convert all the categorical features to one hot encoded vector

StandardScaler
used this to standardized the value which have numerical features

In [17]:
numerical_features=['Age','Experience','Income','Family','CCAvg','Education','Mortgage','Securities Account','CD Account','Online','CreditCard']
categorical_features=['Gender','Home Ownership']
data[numerical_features]=SimpleImputer(strategy='mean').fit_transform(data[numerical_features])
transformer=ColumnTransformer(
transformers=[
    ('scaler',OneHotEncoder(),categorical_features),
    ('num',StandardScaler(),numerical_features),
])
x=transformer.fit_transform(data)
x,y

(array([[ 0.        ,  0.        ,  0.        , ..., -0.25354028,
         -1.22195995, -0.64531434],
        [ 0.        ,  0.        ,  0.        , ..., -0.25354028,
         -1.22195995, -0.64531434],
        [ 0.        ,  0.        ,  0.        , ..., -0.25354028,
         -1.22195995, -0.64531434],
        ...,
        [ 0.        ,  0.        ,  0.        , ..., -0.25354028,
         -1.22195995, -0.64531434],
        [ 0.        ,  0.        ,  0.        , ..., -0.25354028,
          0.82495709, -0.64531434],
        [ 0.        ,  0.        ,  0.        , ..., -0.25354028,
          0.82495709,  1.54963239]]),
 array([0, 0, 0, ..., 0, 0, 0]))

# splitting the dataset 

dataset is splitted to training and testing dataset for training and testing purposes

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(4000, 21) (4000,)
(1000, 21) (1000,)


# MODEL DEFINATION AND MODEL TRANING

In [19]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

# PREDICTING 

In [20]:
prediction=model.predict(x_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# ACCURACY CALCULATION

accuracy_score is used to calculated the accuracy of the model using predictiona and y_test as parameters

In [21]:
print('The accuracy of the model is :',accuracy_score(prediction,y_test))

The accuracy of the model is : 0.953


# SAVING THE FILE

In [22]:
with open('saved_model/model.pkl','wb') as f:
    pickle.dump(model,f)